In [ ]:
import numpy as np

In [ ]:
numpy_arr=np.array([1,2,3,4,5])
print(numpy_arr)

[1 2 3 4 5]


In [ ]:
type([1,2,3,4,5])

list

In [ ]:
type(numpy_arr)

numpy.ndarray

In [ ]:
using_zeros=np.ones((3,10))
print(using_zeros)

[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]


In [ ]:
arr=np.array([[1.,1.],
       [1.,1.],
       [1.,1.]])

In [ ]:
arr=np.arange(1,100,2)
print(arr)

[ 1  3  5  7  9 11 13 15 17 19 21 23 25 27 29 31 33 35 37 39 41 43 45 47
 49 51 53 55 57 59 61 63 65 67 69 71 73 75 77 79 81 83 85 87 89 91 93 95
 97 99]


In [ ]:
arr=np.linspace(1,5,25)

In [ ]:
arr

array([1.        , 1.16666667, 1.33333333, 1.5       , 1.66666667,
       1.83333333, 2.        , 2.16666667, 2.33333333, 2.5       ,
       2.66666667, 2.83333333, 3.        , 3.16666667, 3.33333333,
       3.5       , 3.66666667, 3.83333333, 4.        , 4.16666667,
       4.33333333, 4.5       , 4.66666667, 4.83333333, 5.        ])

In [ ]:
arr=arr.reshape((5,5))

In [ ]:
arr.shape

(5, 5)

In [ ]:
arr[1:3,:2]

array([[1.83333333, 2.        ],
       [2.66666667, 2.83333333]])

In [ ]:
arr=np.arange(0,100,4)
print(arr)

[ 0  4  8 12 16 20 24 28 32 36 40 44 48 52 56 60 64 68 72 76 80 84 88 92
 96]


In [ ]:
bool_arr=arr>60
print(bool_arr)

[False False False False False False False False False False False False
 False False False False  True  True  True  True  True  True  True  True
  True]


In [ ]:
arr[bool_arr]

array([64, 68, 72, 76, 80, 84, 88, 92, 96])

In [ ]:
print(arr>40)
print(arr<80)
arr[(arr>40) & (arr<80)]

[False False False False False False False False False False False  True
  True  True  True  True  True  True  True  True  True  True  True  True
  True]
[ True  True  True  True  True  True  True  True  True  True  True  True
  True  True  True  True  True  True  True  True False False False False
 False]


array([44, 48, 52, 56, 60, 64, 68, 72, 76])

In [ ]:
arr1=np.arange(1,5,1)
arr2=np.arange(2,6,1)

In [ ]:
add_arr=arr1+arr2
print(add_arr)

[3 5 7 9]


<h1>Universal Operators</h1>

In [ ]:
arr=np.linspace(1,5,25)

In [ ]:
print(arr)

[[1.         1.16666667 1.33333333 1.5        1.66666667]
 [1.83333333 2.         2.16666667 2.33333333 2.5       ]
 [2.66666667 2.83333333 3.         3.16666667 3.33333333]
 [3.5        3.66666667 3.83333333 4.         4.16666667]
 [4.33333333 4.5        4.66666667 4.83333333 5.        ]]


In [ ]:
arr=arr.reshape(5,5)

In [ ]:
np.sum(arr)

75.0

In [ ]:
np.sum(arr,axis=0)

array([13.33333333, 14.16666667, 15.        , 15.83333333, 16.66666667])

In [ ]:
np.sum(arr,axis=1)

array([ 6.66666667, 10.83333333, 15.        , 19.16666667, 23.33333333])

In [ ]:
np.var(arr)

1.4444444444444442

In [ ]:
np.var(arr,axis=0)

array([1.38888889, 1.38888889, 1.38888889, 1.38888889, 1.38888889])

In [ ]:
np.var(arr,axis=1)

array([0.05555556, 0.05555556, 0.05555556, 0.05555556, 0.05555556])

In [ ]:
arr.flatten().shape

(25,)

In [ ]:
l1=np.array([1,2,3,4,5]) #no copy
l2=l1
l2[0]=5
print(l1)
print(l2)

[5 2 3 4 5]
[5 2 3 4 5]


In [ ]:
l3=np.array([1,2,3,4,5]) #shallow copy
l4=l3.view()
l3[0]=5
print(l3)
print(l4)

[5 2 3 4 5]
[5 2 3 4 5]


In [ ]:
l5=np.array([1,2,3,4,5]) #deep copy
l6=l5.copy()
l6[0]=5
print(l5)
print(l6)

[1 2 3 4 5]
[5 2 3 4 5]
