Array Creation and Basic Operations

In [34]:
import numpy as np

arr1=np.arange(0,20)
arr1

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [35]:
arr1=arr1.reshape(4,5)
arr1

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [36]:
display(np.zeros(shape=(3,3)))

display(np.ones(shape=(3,3)))

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [37]:
arr2=np.linspace(1,100,10)
arr2

array([  1.,  12.,  23.,  34.,  45.,  56.,  67.,  78.,  89., 100.])

Indexing, Slicing, and Iterating

In [38]:
print(arr1[2,3])
print(arr1[1])
print(arr1[:,-1])

13
[5 6 7 8 9]
[ 4  9 14 19]


In [39]:
arr1[1]=arr1[1][::-1]
arr1

array([[ 0,  1,  2,  3,  4],
       [ 9,  8,  7,  6,  5],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [40]:
random_arr=np.random.randint(1,100,(3,3))
print(random_arr)
print(random_arr[random_arr>50])

[[31 92 41]
 [46 99 86]
 [58 74 83]]
[92 99 86 58 74 83]


Conditional Statements and Boolean Operations

In [41]:
random_arr=np.random.randint(0,100,(5,5))
random_arr

array([[12,  5,  8, 47, 43],
       [17, 83, 97, 55, 71],
       [96, 28, 91, 40, 20],
       [54, 90, 10, 74, 50],
       [82, 16,  1, 43, 72]], dtype=int32)

In [42]:
bool_mask=(random_arr<=70) & (random_arr>=30)
bool_mask

array([[False, False, False,  True,  True],
       [False, False, False,  True, False],
       [False, False, False,  True, False],
       [ True, False, False, False,  True],
       [False, False, False,  True, False]])

In [43]:
random_arr[bool_mask==False]=-1
random_arr

array([[-1, -1, -1, 47, 43],
       [-1, -1, -1, 55, -1],
       [-1, -1, -1, 40, -1],
       [54, -1, -1, -1, 50],
       [-1, -1, -1, 43, -1]], dtype=int32)

Basic Mathematical Operations

In [44]:
rarr1=np.random.randint(1,10,(3,3))
rarr2=np.random.randint(1,10,(3,3))

print(rarr1)
print(rarr2)

[[4 1 2]
 [9 1 8]
 [8 6 8]]
[[1 4 6]
 [7 9 6]
 [5 1 9]]


In [45]:
print(rarr1+rarr2)

[[ 5  5  8]
 [16 10 14]
 [13  7 17]]


In [46]:
print(rarr1-rarr2)

[[ 3 -3 -4]
 [ 2 -8  2]
 [ 3  5 -1]]


In [47]:
print(rarr1*rarr2)

[[ 4  4 12]
 [63  9 48]
 [40  6 72]]


In [48]:
print(rarr1/rarr2)

[[4.         0.25       0.33333333]
 [1.28571429 0.11111111 1.33333333]
 [1.6        6.         0.88888889]]


In [49]:
print(rarr1.dot(rarr2))

[[ 21  27  48]
 [ 56  53 132]
 [ 90  94 156]]


Universal Functions

In [50]:
print(random_arr)

print(f"Mean: {np.mean(random_arr)}")
print(f"Std. Deviation: {np.std(random_arr,axis=1)}")
print(f"Variance: {np.var(random_arr,axis=0)}")
print(f"Median: {np.median(random_arr)}")
print(f"Min: {random_arr.min(axis=1)}")
print(f"Max: {random_arr.max(axis=1)}")

[[-1 -1 -1 47 43]
 [-1 -1 -1 55 -1]
 [-1 -1 -1 40 -1]
 [54 -1 -1 -1 50]
 [-1 -1 -1 43 -1]]
Mean: 12.56
Std. Deviation: [22.57077757 22.4        16.4        25.99538421 17.6       ]
Variance: [484.     0.     0.   382.56 546.4 ]
Median: -1.0
Min: [-1 -1 -1 -1 -1]
Max: [47 55 40 54 43]


Shape Manipulation

In [51]:
rarr=np.random.randint(0,100,24)
rarr

array([41, 50, 24, 63, 63, 43,  0, 63, 37, 40, 41, 40, 44, 40, 67, 31, 43,
       34, 39,  8, 31, 38, 94, 53], dtype=int32)

In [52]:
rarr=rarr.reshape(4,6)
rarr

array([[41, 50, 24, 63, 63, 43],
       [ 0, 63, 37, 40, 41, 40],
       [44, 40, 67, 31, 43, 34],
       [39,  8, 31, 38, 94, 53]], dtype=int32)

In [53]:
rarr.flatten()

array([41, 50, 24, 63, 63, 43,  0, 63, 37, 40, 41, 40, 44, 40, 67, 31, 43,
       34, 39,  8, 31, 38, 94, 53], dtype=int32)

In [54]:
rarr=rarr.transpose()
rarr

array([[41,  0, 44, 39],
       [50, 63, 40,  8],
       [24, 37, 67, 31],
       [63, 40, 31, 38],
       [63, 41, 43, 94],
       [43, 40, 34, 53]], dtype=int32)

In [55]:
temp_arr1=np.random.randint(0,10,(3,3))
temp_arr2=np.random.randint(11,20,(3,3))

arr=np.vstack((temp_arr1,temp_arr2))
print(arr)

print()

temp_arr3=np.random.randint(21,30,(6,6))

arr=np.hstack((arr,temp_arr3))

print(arr)

[[ 1  0  4]
 [ 4  6  3]
 [ 1  4  4]
 [18 13 11]
 [19 13 15]
 [15 13 12]]

[[ 1  0  4 22 24 23 23 24 25]
 [ 4  6  3 29 24 29 26 23 29]
 [ 1  4  4 22 26 25 25 25 25]
 [18 13 11 25 26 27 27 25 21]
 [19 13 15 24 26 24 26 27 23]
 [15 13 12 21 26 23 22 28 24]]


Copy Methods

In [56]:
arr=np.random.randint(0,100,(3,3))
print(arr)

[[56 79  7]
 [76 71 24]
 [26 85 99]]


In [57]:
arr_copy=arr
arr_copy[0][0]=-1
#This is more like a reference to the original array
print(arr)
print(arr_copy)

[[-1 79  7]
 [76 71 24]
 [26 85 99]]
[[-1 79  7]
 [76 71 24]
 [26 85 99]]


In [58]:
arr_copy=arr.view()
arr_copy[1][1]=-1
#This is the view of the original array i.e. has the same memory location
print(arr)
print(arr_copy)

[[-1 79  7]
 [76 -1 24]
 [26 85 99]]
[[-1 79  7]
 [76 -1 24]
 [26 85 99]]


In [59]:
arr_copy=arr.copy()
arr_copy[2][2]=-1
#Here a complete new copy is created with the same values as the original but without directly referencing it
print(arr)
print(arr_copy)

[[-1 79  7]
 [76 -1 24]
 [26 85 99]]
[[-1 79  7]
 [76 -1 24]
 [26 85 -1]]


Handling NULL Values

In [60]:
arr=np.random.rand(4,4)
np.fill_diagonal(a=arr,val=np.nan)
arr

array([[       nan, 0.6243679 , 0.18357449, 0.43226471],
       [0.24222607,        nan, 0.61190332, 0.93449712],
       [0.75245452, 0.0014004 ,        nan, 0.83316102],
       [0.77198043, 0.05912241, 0.35781017,        nan]])

In [61]:
bool_mask=np.isnan(arr)
bool_mask

array([[ True, False, False, False],
       [False,  True, False, False],
       [False, False,  True, False],
       [False, False, False,  True]])

In [62]:
np.nanmean(arr)

np.float64(0.48373021266913047)

Advanced Challenge

In [63]:
arr=np.random.randint(1,100,(10,10))
arr

array([[84, 15, 51, 86, 68, 22,  4, 50, 36, 75],
       [89, 24, 90, 15, 40, 24, 10, 18, 40,  1],
       [49, 30, 11, 48, 24, 49, 17, 76, 86, 73],
       [79, 80, 33, 44, 66, 98, 47,  7, 80, 90],
       [89, 88,  1, 30, 11, 94, 47, 89, 90, 95],
       [36, 37, 74, 77, 27, 21, 27, 27, 94, 40],
       [60, 37,  7,  5, 58, 43, 95, 88, 48, 67],
       [25, 88, 96, 44, 85, 76, 89, 31, 23, 28],
       [46, 69, 60, 63, 77, 76, 99, 50, 56,  1],
       [24, 40, 55, 28, 59, 34, 55, 33, 97, 58]], dtype=int32)

In [64]:
y=arr.flatten()
y=np.unique(y)
y[-5:]

array([95, 96, 97, 98, 99], dtype=int32)

In [65]:
temp=np.cumsum(arr,axis=1)
print(temp)
temp[:][10:]=temp[:][10:]-temp[:][:-10]
temp[:][10-1:]/10

[[ 84  99 150 236 304 326 330 380 416 491]
 [ 89 113 203 218 258 282 292 310 350 351]
 [ 49  79  90 138 162 211 228 304 390 463]
 [ 79 159 192 236 302 400 447 454 534 624]
 [ 89 177 178 208 219 313 360 449 539 634]
 [ 36  73 147 224 251 272 299 326 420 460]
 [ 60  97 104 109 167 210 305 393 441 508]
 [ 25 113 209 253 338 414 503 534 557 585]
 [ 46 115 175 238 315 391 490 540 596 597]
 [ 24  64 119 147 206 240 295 328 425 483]]


array([[ 2.4,  6.4, 11.9, 14.7, 20.6, 24. , 29.5, 32.8, 42.5, 48.3]])

In [66]:
sum_column=arr.sum(axis=0)
norm=arr/sum_column
print(norm.sum(axis=0))
norm

[1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]


array([[0.14457831, 0.02952756, 0.10669456, 0.19545455, 0.13203883,
        0.04096834, 0.00816327, 0.10660981, 0.05538462, 0.14204545],
       [0.15318417, 0.04724409, 0.18828452, 0.03409091, 0.0776699 ,
        0.04469274, 0.02040816, 0.03837953, 0.06153846, 0.00189394],
       [0.08433735, 0.05905512, 0.02301255, 0.10909091, 0.04660194,
        0.09124767, 0.03469388, 0.16204691, 0.13230769, 0.13825758],
       [0.13597246, 0.15748031, 0.06903766, 0.1       , 0.12815534,
        0.18249534, 0.09591837, 0.01492537, 0.12307692, 0.17045455],
       [0.15318417, 0.17322835, 0.00209205, 0.06818182, 0.02135922,
        0.17504655, 0.09591837, 0.18976546, 0.13846154, 0.17992424],
       [0.06196213, 0.07283465, 0.15481172, 0.175     , 0.05242718,
        0.03910615, 0.05510204, 0.0575693 , 0.14461538, 0.07575758],
       [0.10327022, 0.07283465, 0.01464435, 0.01136364, 0.11262136,
        0.08007449, 0.19387755, 0.18763326, 0.07384615, 0.12689394],
       [0.04302926, 0.17322835, 0.2008368